### PR TITLE
Multiple enhancements

### LINKED ISSUE #3: input_text limitation
Hi, and thanks for a great integration.  Just what I was looking for.
I am currently using it to make voice announcements more dynamic and fun.  However, I am often hitting the limit if 255 characters in the input_text to create the request.
For instance I want it to generate a weather report based on a lot of sensor data, but that request very easily exceeds 255 characters.
As far as I know, there is no such limit in a servce call, as as service_data element can be of any size and type.

So would it be an option to extend this integration with a service call that can be used instead of/in addition to the input_text?

### LINKED ISSUE #4: Migrate to gpt-3.5-turbo
I tried to change the `model` from the default `text-davinci-003` to `gpt-3.5-turbo`
But it seems like that model is not usable for the integration:

```
'This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?' error_param=model error_type=invalid_request_error message='OpenAI API error received' 

...

openai.error.InvalidRequestError: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?
```

Now, I don't know enough about the different models and endpoints, so it might be that the "chat" endpoint can't be used, but it looks from the documentation as if the chat endpoint and gpt-3.5-turbo is the best option:

> [Chat vs Completions](https://platform.openai.com/docs/guides/chat/chat-vs-completions)
Because gpt-3.5-turbo performs at a similar capability to text-davinci-003 but at 10% the price per token, we recommend gpt-3.5-turbo for most use cases.

### PR DESCRIPTION
**Pull request by Olen**
- Add a service call to send requests (fixes #3)
- Replace OpenAi call to use chatgpt-3.5 (fix #4)
- Add more info to attributes (implements #5)

Also includes some code cleanup and docstrings etc. to keep VSCode from complaining too much.

### CODE REVIEW

**Comment by Olen** [comment]
There is a problem somewhere.  
 I get a bunch of these

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 351, in handle_get_services
    descriptions = await async_get_all_descriptions(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 603, in async_get_all_descriptions
    domain_yaml = loaded[domain]
KeyError: 'wake_on_lan'
```

Need to investigate

**Comment by Olen** [comment]
Found the bug.  DOMAIN needs to be the same as the integration name.

NOW it seems to be working fine

**Comment by Hassassistant** [comment]
awesome work Olen.
I would love to spend time tweaking and testing this but I have had no time since first releasing this.
Appreciate your work and effort greatly.

**Comment by Jokod** [comment]
Since OpenAI has removed the 'text-davinci-003' model, it becomes essential to address the change in using the 'gpt-3.5-turbo' model.

Without this, the plugin does not work without having to tinker with the sensor.py.

Thank you.

**Pull request merged**
